name: bonyeza_kazi
description: "Bonyeza Kazi is a job based service where -: Users are able to
  identify labourers such as Plumbers, electricians and/ or cleaning ladies etc.
  Identify professions workers such as event organisers, tailors, mechanics etc.
  There are 2 parties involved: 1) The party providing the service(SP). 2) The
  party asking for the service(Client)."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #responsive_framework
  responsive_framework: ^0.0.8

  #font / styling / animation /responsive
  cupertino_icons: ^0.1.3
  division: ^0.8.8
  line_awesome_flutter: ^1.0.1
  responsive_widgets: ^2.0.1
  persistent_bottom_nav_bar: ^2.0.5
  carousel_slider: ^2.2.1
  animation_director: ^0.1.1
  cached_network_image: ^2.3.1
  smooth_star_rating: 1.1.1
  tab_indicator_styler: ^1.0.0
  photo_view: ^0.9.2
  icon_font_generator: ^1.0.0
  flushbar: ^1.10.4
  animations: ^1.1.2
  page_view_indicators: ^1.4.0
  loading_indicator: ^1.2.0
  flutter_svg: ^0.19.0

  #state management
  flutter_bloc: ^6.0.4

  #local storage
  shared_preferences: ^0.5.10

  #http api
  dio: ^3.0.10
  dio_http_cache: ^0.2.6

  #injection dependency
  injectable: ^1.0.4

  #code generators
  freezed_annotation: ^0.11.0+1
  json_annotation: ^3.0.1

  #funtional programming /immutable list
  dartz: ^0.9.1
  kt_dart: ^0.7.0+1

  #navigation manager
  auto_route: ^0.6.7

  #google maps/ locaton/ get direction
  google_maps_flutter: ^0.5.31
  location: ^3.0.2

  #share /call / phone
  share: ^0.6.4+3
  flutter_phone_state: ^0.5.8

  #form handling
  form_field_validator: ^1.0.1
  smart_form: ^0.0.3

  #security
  flutter_secure_storage: ^3.3.3
  #image uploader
  image_picker: ^0.6.7+7
  multi_image_picker: ^4.7.14

  #db
  firebase_storage: ^4.0.0
  cloud_firestore: ^0.14.0+2
  firebase_core: ^0.5.0
  firebase_auth: ^0.18.1+2

  #push notifications
  firebase_messaging: ^7.0.0

  #miscellaneous
  meta: ^1.1.8
  dart_random_choice: ^0.0.2
  latlong: ^0.6.1
  android_intent: ^0.3.6+12
  uuid: 2.2.2
  rxdart: ^0.24.1
  country_code_picker: ^1.4.0
  date_time_picker: ^1.0.1
  permission_handler: ^5.0.0
  contacts_service: ^0.3.10
  flutter_open_whatsapp: ^0.1.2
  rx_shared_preferences: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  injectable_generator: ^1.0.4

  build_runner: ^1.10.2
  device_preview: ^0.4.8
  freezed: ^0.11.6
  json_serializable: ^3.4.1
  auto_route_generator: ^0.6.8

flutter:
  uses-material-design: true

  assets:
    - assets/images/electrician.jpg
    - assets/images/builder.jpg
    - assets/images/NYAKUA.png
    - assets/icons/plumbing.svg

  fonts:
    - family: UiIcons
      fonts:
        - asset: assets/iconfont/ui_icons.ttf
    - family: MyFlutterApp
      fonts:
        - asset: assets/iconfont/MyFlutterApp.ttf
    - family: Avenir
      fonts:
        - asset: assets/fonts/Avenir_Next_Pro/AvenirLTStd-Black.otf
          weight: 900
        - asset: assets/fonts/Avenir_Next_Pro/AvenirLTStd-Heavy.otf
          weight: 800
        - asset: assets/fonts/Avenir_Next_Pro/AvenirLTStd-Medium.otf
          weight: 500
        - asset: assets/fonts/Avenir_Next_Pro/AvenirLTStd-Book.otf
          weight: 400
        - asset: assets/fonts/Avenir_Next_Pro/AvenirLTStd-Light.otf
          weight: 300

    - family: AvenirRound
      fonts:
        - asset: assets/fonts/Avenir_Next_Round/AvenirNextRoundedProBold.ttf
          weight: 700
        - asset: assets/fonts/Avenir_Next_Round/AvenirNextRoundedProDemi.ttf
          weight: 600
        - asset: assets/fonts/Avenir_Next_Round/AvenirNextRoundedProMedium.ttf
          weight: 500
        - asset: assets/fonts/Avenir_Next_Round/AvenirNextRoundedProRegular.ttf
          weight: 400
